sudo: false
language: ruby
before_install: gem update --system
cache: bundler
rvm:
  - 2.2
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-9.1.6.0

env:
  matrix:
    - RAILS='~> 4.2.0'
    - RAILS='~> 5.0.0'
    - RAILS='~> 5.1.0'
    - RAILS='~> 5.2.0'
    - RAILS='~> 6.0.0.beta3'

matrix:
  allow_failures:
    - env: RAILS='~> 4.2.0'
      rvm: jruby-9.1.6.0
    - env: RAILS='~> 5.0.0'
      rvm: jruby-9.1.6.0
    - env: RAILS='~> 5.1.0'
      rvm: jruby-9.1.6.0
    - env: RAILS='~> 5.2.0'
      rvm: jruby-9.1.6.0
    - env: RAILS='~> 6.0.0.beta3'
      rvm: 2.2
    - env: RAILS='~> 6.0.0.beta3'
      rvm: 2.3.8
    - env: RAILS='~> 6.0.0.beta3'
      rvm: 2.4.5
    - env: RAILS='~> 6.0.0.beta3'
      rvm: jruby-9.1.6.0
